### ISSUE TITLE
Bug: `mashing_probability` tests wrong variable

### ISSUE THREAD

**Issue by pjho** [academia-edu/dejunk#2]
Hey there,

Thanks for this library. I've been going through source code and have a question about the logic in the `mashing_probability` function [here](https://github.com/academia-edu/dejunk/blob/master/lib/dejunk.rb#L232).

I don't know ruby too well so sorry if I'm misunderstanding this but in the `elsif` test, should that not be testing against `bigram`? If `f` is the result of `mashing_bigram_frequencies[bigram]` it should either be a `float` or `nil` no?

``` ruby

  def mashing_probability(bigram)
    if (f = mashing_bigram_frequencies[bigram])
      f
    elsif f =~ /[a-z]{2}/i # <- should this be testing bigram?
      0.0005
    else
      1e-6
    end
  end

```

Anyways, sorry if I've misunderstood & thanks again. I'm learning heaps looking at the approach you've taken here :+1:.

**Comment by patbl** [comment]
You're right that this is a bug. I can fix it, but that causes a couple of specs to fail. (It thinks that "Zoology" and "Weight" are junk.) I can fix them by lowering the mashing probability from 0.0005 to around 8e-5, but I'm not sure that that's the right approach. You're probably more familiar with the code than I am.

@djudd (who wrote this gem) is no longer is working at the company, but maybe he's still interested.

**Comment by pjho** [comment]
Hey, all good. Not sure the correct approach either. Obviously those are some pretty common words that you don't want to invalidate. I haven't played around with it too much yet so I'll post back here if I come up with something. I'm writing a Javascript port of the gem so I can adjust it there without impacting anyone. Had me stumped for a while trying to work out what was going on there though. 

Hope that's all good to port to JS. According to the license it should be. I plan to put it up on NPM if I can get it all working well enough. I couldn't find anything similar for JS so would be nice to have it available. I'll keep references to the original library/authors in the readme, let me know if thats enough. If you want it to remain under academia-edu let me know, I'm not adding anything other than rewriting syntax. 

Cheers.

**Comment by djudd** [comment]
1. Yeah that's a bug and I think the correct solution is probably to just remove the broken `elsif` branch, unless someone is prepared to go systematically retest on a big list of words.

2. IANAL but I think the Apache license gives you the right to rewrite in JS with or without further permission from us. But thanks for checking in! Glad this might prove useful to someone else.

**Comment by djudd** [comment]
Oh, and FWIW: I don't know your usecase, but you'll probably want some domain-specific whitelists. Probably that should be in the Readme, come to think of it...

**Comment by pjho** [comment]
Cool. Yeah seems if it's been working well in production not much point in "fixing" it now. 

Cheers for the heads up re: whitelists, I'll have a play and see how it goes for me.

I'm going to go ahead and close this issue since I opened it... hope thats good with you guys. 

 Cheers again. 👍

**Comment by nate00** [comment]
I'm going to reopen since this is a bug that we ought to fix. Thanks for spotting it @pjho, and feel free to unsubscribe from this issue if you don't want any more notifications.
